//go:build linux

package platform

import (
	"reflect"
	"strings"
	"testing"
)

func TestParseResolvConf(t *testing.T) {
	body := `
# generated by systemd-resolved
; another comment style
search example.lan
nameserver 192.168.1.1
nameserver   10.0.0.53
nameserver fe80::1%eth0
nameserver 192.168.1.1
options edns0 trust-ad
nameserver not-an-address
nameserver
`
	got := parseResolvConf(strings.NewReader(body))
	want := []string{"192.168.1.1", "10.0.0.53", "fe80::1"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("nameservers = %v, want %v (file order, deduped, zone stripped)", got, want)
	}
}

func TestParseResolvConfEmpty(t *testing.T) {
	if got := parseResolvConf(strings.NewReader("search example.lan\n")); len(got) != 0 {
		t.Fatalf("nameservers = %v, want none", got)
	}
}
